languageCode  = "en-us"
title         = "The joy of programming"
baseurl       = "https://joy.pm/"
theme         = "joy.pm"
publishdir    = "public"

[author]
    name = "Rafa de Castro"
    copyright = "(c) 2019 Rafa de Castro"
